### ISSUE TITLE
Drawing order incorrect in more complex images

### ISSUE THREAD

**Issue by alexparlett** [shnewto/edges#1]
Thanks for the library - find it really useful.

Drawing order is not quite correct in a more complex image.

<img width="343" alt="image" src="https://github.com/shnewto/edges/assets/2347963/b4d3b756-5080-4bf6-bf01-f1e89d8ff0f7">

![Uvall](https://github.com/shnewto/edges/assets/2347963/3b1707bb-fb82-4240-808d-4d3704c376dc)

Blown up the points to illustrate.

````
                let edges = Edges::from(image);
                let mut bounds = edges.single_image_edge_translated();
````

**Comment by shnewto** [comment]
Oh interesting, yeah I'll take a look 🤔  Thanks for raising the issue! And for including the sprite 🙏 😄 

Happy to hear it's been a useful crate for you ❤️

**Comment by shnewto** [comment]
wow that was a doozy of a bug, but I think it's tackled now after #2 

if you're up for it @alexparlett, I'd love it if you made a pr to add that sprite to the `assets` directory so it can be used for manual regression checks?

thanks again for raising the issue, your example sprite was perfect for debugging the behavior and looking back on the bug now, it explains some flakiness I've bumped into and wasn't able to pinpoint the cause.

**Comment by shnewto** [comment]
oh also, here's the edges drawn after the changes (now publised to crates io)
<img width="331" alt="image" src="https://github.com/shnewto/edges/assets/5607902/62d2bdd2-f51e-44a2-8b6a-e2b74b875208">
