### ISSUE TITLE
Too many edges generated for simple shape

### ISSUE THREAD

**Issue by mantasarm** [shnewto/edges#3]
![image](https://github.com/user-attachments/assets/b72b9549-4a81-4f8e-94a0-ffda6a0b5f89)

For this shape a 8x8 texture, with a single pixel missing, the `multi_image_edges_raw()` function for some reason **generates 8 edges instead of just 2**. Happens everytime. A fix or solution would be very appreciated. I'm happy to provide anymore details needed.

**Comment by shnewto** [comment]
Hi @mantasarm thanks for raising this issue! I'll be digging into this over the next couple days.

**Comment by shnewto** [comment]
This is a really good bug 😵 Working on it I realized what a wrench single pixel boundaries throw into my approach. Part of the algorithm for sorting points into "drawing order" is using a distance of 1 pixel to decide what the neighboring edges are. When there's only 1 pixel between two distinct "shapes with edges" , or when a single pixel is shared between edges, my approach is breaking down. But it doesn't have to, and of course, shouldn't break down. 

Thanks a ton for raising this issue @mantasarm, it might take me a minute to sort out the right way to handle this but it's a really good thing to have spotted and for me to able to address.

**Comment by shnewto** [comment]
@mantasarm we just had a major rework done by @salam99823 and they had your use case in mind for a large part of it. I believe version `0.4` now addresses this specific scenario 🚀 thanks again for raising this issue!
