### ISSUE TITLE
Begin using GitHub releases for Change 

### ISSUE THREAD

**Issue by shnewto** [shnewto/edges#8]
There is some really nice GitHub native functionality for describing releases, linking commits and writing migration guides. It lives in the "Releases" for a repo. We haven't been using it yet but I'd favor it over tracking changes in a separate changelog or release notes file.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/effe0c00-bd3d-4960-aeef-7be6bff4faf1">

☝️ on the right side of a repo's home page

👇 once you've clicked on the Releases link and clicked to create a new release
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/262f9164-9081-4ca3-ac27-086a12cb0340">

**Comment by shnewto** [comment]
@salam99823 thanks a ton for your changelog and release notes! I should have been clearer that this is what I was thinking when I suggested that I could use your help doing release notes and migration guides before but there's no reason we can't still start now.

**Comment by shnewto** [comment]
here's a previous release using GitHub releases from the `bevy_collider_gen` project https://github.com/shnewto/bevy_collider_gen/releases

**Comment by salam99823** [comment]
Does this [release](https://github.com/shnewto/edges/releases/tag/0.5.0) look good?

**Comment by shnewto** [comment]
@salam99823 that's fantastic, thank you again for your great contributions!
